// Type definitions for Atom (v${version})
// Project: https://atom.io/
// Definitions by: vvakame <https://github.com/vvakame/>
// Definitions: https://github.com/borisyankov/DefinitelyTyped

// Generated by: https://github.com/david-driscoll/atom-typescript-generator
// Generation tool by david-driscoll <https://github.com/david-driscoll/>
//${refs}

//${content}

// Found @ https://github.com/atom/atom/blob/master/exports/atom.coffee
declare module "fs-plus" {
    import fs = require("fs");
    export = fs;
}

declare var atom: Atom.Atom;
