// Type definitions for ${name} (v${version})
// Project: https://github.com/atom/${name}
// Definitions by: david-driscoll <https://github.com/david-driscoll/>
// Definitions: https://github.com/borisyankov/DefinitelyTyped

// Generated by: https://github.com/david-driscoll/atom-typescript-generator
// Generation tool by david-driscoll <https://github.com/david-driscoll/>
//${refs}

// Found @ https://github.com/atom/atom-space-pen-views/blob/master/src/main.coffee
declare module "${name}" {
    var View: SpacePen.ViewStatic;
    var jQuery: JQueryStatic;
    var $: SpacePen.$;
    var $$: SpacePen.$$;
    var $$$: SpacePen.$$$;
    var TextEditorView: typeof AtomSpacePenViews.TextEditorView;
    var SelectListView: AtomSpacePenViews.SelectListViewStatic;
    var ScrollView: typeof AtomSpacePenViews.ScrollView;
}

declare module AtomSpacePenViews {
    interface SelectListViewStatic {
        constructor(): AtomSpacePenViews.SelectListView;
    }
}
