// Type definitions for ${name} (v${version})
// Project: https://github.com/atom/${name}
// Definitions by: david-driscoll <https://github.com/david-driscoll/>
// Definitions: https://github.com/borisyankov/DefinitelyTyped

// Generated by: https://github.com/david-driscoll/atom-typescript-generator
// Generation tool by david-driscoll <https://github.com/david-driscoll/>
//${refs}

// Found @ https://github.com/atom/event-kit/blob/master/src/event-kit.coffee
declare module "${name}" {
    var Emitter: EventKit.Emitter;
    var Disposable: EventKit.Disposable;
    var CompositeDisposable: EventKit.CompositeDisposable;
}
