// Type definitions for ${name} (v${version})
// Project: https://github.com/atom/${name}
// Definitions by: david-driscoll <https://github.com/david-driscoll/>
// Definitions: https://github.com/borisyankov/DefinitelyTyped

// Generated by: https://github.com/david-driscoll/atom-typescript-generator
// Generation tool by david-driscoll <https://github.com/david-driscoll/>
//${refs}

// Found @ https://github.com/atom/first-mate/blob/master/src/first-mate.coffee
declare module "${name}" {
    var ScopeSelector: FirstMate.ScopeSelector;
    var GrammarRegistry: FirstMate.GrammarRegistry;
    var Grammar: FirstMate.Grammar;
}
