// Type definitions for ${name} (v${version})
// Project: https://github.com/atom/${name}
// Definitions by: david-driscoll <https://github.com/david-driscoll/>
// Definitions: https://github.com/borisyankov/DefinitelyTyped

// Generated by: https://github.com/david-driscoll/atom-typescript-generator
// Generation tool by david-driscoll <https://github.com/david-driscoll/>
//${refs}

// Found @ https://github.com/atom/scandal/blob/master/src/scandal.coffee
declare module "${name}" {
    var search: any;
    var replace: any;
    var PathSearcher: typeof Scandal.PathSearcher;
    var PathScanner: typeof Scandal.PathScanner;
    var PathReplacer: any;
}
