// Type definitions for ${name} (v${version})
// Project: https://github.com/atom/${name}
// Definitions by: david-driscoll <https://github.com/david-driscoll/>
// Definitions: https://github.com/borisyankov/DefinitelyTyped

// Generated by: https://github.com/david-driscoll/atom-typescript-generator
// Generation tool by david-driscoll <https://github.com/david-driscoll/>
//${refs}

// Found @ https://github.com/atom/space-pen/blob/master/src/space-pen.coffee
declare module "${name}" {\
    var View : SpacePen.ViewStatic;
    var jQuery : JQueryStatic;
    var $ : JQueryStatic;
    function $$(fn: Function) => JQuery;
    function $$$(fn: Function) => Node;
}
