// Type definitions for ${name} (v${version})
// Project: https://github.com/atom/${name}
// Definitions by: david-driscoll <https://github.com/david-driscoll/>
// Definitions: https://github.com/borisyankov/DefinitelyTyped

// Generated by: https://github.com/david-driscoll/atom-typescript-generator
// Generation tool by david-driscoll <https://github.com/david-driscoll/>
//${refs}

// Found @ https://github.com/atom/status-bar/blob/master/lib/main.coffee
declare module "${name}" {
    function activate(state?: any);
    function activate();
}
